[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
script = 'scripts'
cache_path  = 'cache_forge'
solc = "0.8.24"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
via_ir = true
