name: Voucher Smart Contract CI

on:
  push:
    branches: ["**"]

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Check Format
        run: npm run check-format

      - name: Generate UML
        run: npm run uml

      - name: Setup Foundry Toolchain
        uses: foundry-rs/foundry-toolchain@v1

      - name: Start Bellecour Fork
        run: |
          nohup anvil --host 0.0.0.0 --port 8545 --hardfork berlin --fork-url https://bellecour.iex.ec --chain-id 134 --gas-limit 6700000 --gas-price 0 &
      

      - name: Wait for Fork
        timeout-minutes: 2
        run: |
          while ! nc -z 127.0.0.1 8545; do sleep 1; done
          echo "Bellecour fork ready"

      - name: Run Tests
        run: npm run test --bail

      - name: Run Coverage
        run: npm run coverage
      
      - name: List .openzeppelin directory contents
        run: |
          echo "Contents of .openzeppelin directory:"
          ls -R .openzeppelin

      - name: Run Upgrade Test
        run: npm run upgrade-local-fork
        

      - name: Upload Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: iExecBlockchainComputing/iexec-voucher-contracts

      - name: Slither Analysis
        uses: crytic/slither-action@v0.4.0
        with:
          target: "contracts/"
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
          fail-on: none # TODO set this to high or other
          sarif: results.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
