on:
  workflow_dispatch:
      inputs:
        network:
            description: 'Network'
            required: true
            default: 'hardhat'
            type: choice
            options:
            - hardhat
            - bellecour

jobs:
  upgrade:
    runs-on: ubuntu-latest
    environment: ${{ inputs.network }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - run: | # TODO: Commit all file changed and create PR
        echo "Network: $NETWORK"
        echo "Fake: $FAKE_PRIVATE_KEY"
        if [ "$NETWORK" == 'hardhat' ]; then 
          export IS_LOCAL_FORK=true
          echo "IS_LOCAL_FORK: $IS_LOCAL_FORK"
        fi
        npm run upgrade -- --network $NETWORK
      env:
        NETWORK: ${{ inputs.network }}
        FAKE_PRIVATE_KEY: ${{ inputs.network == 'hardhat' && secrets.FAKE_PRIVATE_KEY }}
